#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
## Requirements:
## The redirection must be a “301 Moved Permanently”
## Using what you did with 1-install_nginx_web_server, write 3-redirection\
### so that it configures a brand new Ubuntu machine to the requirements\
## asked in this task

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
    listen		[::]:80 default_server;

    root		/var/www/html;
    index		index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
