#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
#+ Distribute requests using a roundrobin algorithm
#+ HAproxy that can be managed via an init script

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get install -y haproxy=2.5.\*

echo "ENABLED=1" > /etc/default/haproxy

# Send traffic to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 426036-web-01 52.73.243.18 check
   server 426036-web-02 35.153.57.40 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
