#!/usr/bin/env bash
# A script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Check for update and install HAproxy on my lb-01 server
apt-get -y update
apt-get install -y

# Ensure haproxy started by init script
echo "ENABLED=1" > /etc/default/haproxy

# Configure the config file
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server web-01 426036-web-01 52.73.243.18:80 check
   server web-02 426036-web-02 35.153.57.40:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
