#!/usr/bin/env bash
# Installs MySQL on servers version 5.7.x
sudo apt update
ps aux | grep apt
sudo apt clean
sudo dpkg --configure -a
sudo wget -O mysql57 https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57 && sudo chmod +x mysql57 && sudo ./mysql57
