#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
# Display hours from 0 to 12
# Display minutes from 1 to 59
hour=0
while [[ $hour -le 12 ]]; do
    min=1
    echo "Hour: $hour"
    while [[ $min -le 59 ]]; do
	echo $min
	((min++))
    done
    ((hour++))
done
