#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements:
# Localhost resolves to 127.0.0.2
# Facebook.com resolves to 8.8.8.8
sudo cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '$ a 8.8.8.8\tfacebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
